swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /get_keys:
    get:
      operationId: "manager-redis.get_keys"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: 'Example: http://127.0.0.1:5000/api/get_keys?keys=4.3.2.1.dnsbl.sympla.com.br.'
      parameters:
        - name: keys
          in: query
          description: "List of keys []"
          type: array
          items:
            type: string
          required: True
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
      security:
        - apiKey: []
  /add_keys:
    post:
      operationId: "manager-redis.add_keys"
      tags:
        - "Add_Keys"
      summary: "To add a new key on DNS Server"
      description: 'Example: [{"name": "4.3.2.1.dnsbl.sympla.com.br.", "value": {"fqdn": "4.3.2.1.dnsbl.sympla.com.br.","ipv4_public_ips": ["127.0.0.1"],"ttl": 300,"origin": "tor"}}]'
      parameters:
        - name: keys
          in: body
          schema:
            type: array
          required: True
      responses:
        200:
          description: "Successful add keys operation"
          schema:
            type: "string"
securityDefinitions:
  basic:
    type: basic
    x-basicInfoFunc: security.basic_auth
  apiKey:
    type: apiKey
    in: header
    name: X-Auth
    x-apikeyInfoFunc: security.apikey_auth
